#!/bin/sh

clock=$(date '+%I')

case "$clock" in
	"00") icon="" ;;
	"01") icon="" ;;
	"02") icon="" ;;
	"03") icon="" ;;
	"04") icon="" ;;
	"05") icon="" ;;
	"06") icon="" ;;
	"07") icon="" ;;
	"08") icon="" ;;
	"09") icon="" ;;
	"10") icon="" ;;
	"11") icon="" ;;
	"12") icon="" ;;
esac

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" ;;
	3) notify-send " Time/date module" "• Left click: show the month via \`cal\`" ;;
	6) setsid -f st -e vim "$0" ;;
esac

printf " %s\n" "$(date "+%d %b %Y (%a) $icon %I:%M%p |")"
