#!/bin/sh

case $BLOCK_BUTTON in
	1) setsid -f st -e htop ;;
	3) notify-send " Memory module" "• Left click: Open htop" ;;
	6) setsid -f st -e vim "$0" ;;
esac

free --mebi | awk '/Mem:/ {printf("  %.2fGiB", $3/1024)}'
printf " |" "\\n"
