#!/bin/sh

# Prints the current volume.

case $BLOCK_BUTTON in
	1) pamixer --toggle-mute ;;
	2) ;;
    3) notify-send " Volume module" "\n• Left click: Mutes
• Middle click: ?
• Right click: This help" ;;
	6) setsid -f st -e vim "$0" ;;
esac

# Check if muted first
if pamixer --get-mute > /dev/null 2>&1 && [ "$(pamixer --get-mute)" = "true" ]; then
	echo " |" && exit
fi

# Get volume percentage
vol="$(pamixer --get-volume)"

# Choose icon based on volume level
case 1 in
	$((vol >= 70)) ) icon=" " ;;
	$((vol >= 30)) ) icon=" " ;;
	$((vol >= 1)) ) icon=" " ;;
	* ) echo " |" && exit ;;
esac

echo "$icon$vol% |"
